### ISSUE TITLE
与 Outlook.com 不兼容

### ISSUE THREAD

**Issue by Master-Hash** [SuperKenVery/nju-schedule-ics#8]
复现步骤：

1. 在 outlook.live.com 相应界面订阅 ics；
2. 可以订阅成功，但是不显示任何内容；
3. 手动下载 ics 文件并导入，也不显示任何内容；
4. 用 Thunderbird 或其他日历软件导入，可以正确显示内容。

**Comment by SuperKenVery** [comment]
emmmmm 让我看看

难道是outlook有什么奇怪的要求

**Comment by SuperKenVery** [comment]
好家伙，居然是这个时区导致的
https://github.com/SuperKenVery/nju-schedule-ics/blob/fb3aa4206763f66b9759bf6c24a824757e84f90e/src/schedule/calendar.rs#L47-L51

**Comment by SuperKenVery** [comment]
https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-cant-read-timezone-in-ics-file-a-slew-of/495cadf9-4630-48b5-99ce-88d94980f289?page=1

**Comment by SuperKenVery** [comment]
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/e5dea96d-f624-41fb-a4f3-202e4b5ad947">
确实是我生成的文件不符合标准了……得修一下

**Comment by Master-Hash** [comment]
谢谢你！
